version: "1"

services:
  redis:
    container_name: aut-redis
    image: redis:7.0.11
    hostname: redis
    ports:
      - "6379:6379"
    restart: always

  rabbit:
    container_name: aut-rabbit
    hostname: rabbit
    image: rabbitmq:3.11.15
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  automation:
    container_name: aut-server
    image: ibrahimnasri24/ubility-automation:1.0.0
    hostname: automation
    command: bash -c "echo 'SECRET_KEY = ${AUTOMATION_SECRET_KEY}' > /app/.env && az login --service-principal --user='${AZURE_CLIENT_ID}' --password='${AZURE_CLIENT_SECRET}' --tenant='${AZURE_TENANT_ID}' && /app/run.sh"
    volumes:
      - .automation-server/scripts:/app/scripts
    expose:
      - "5000"
    ports:
      - "5000:5000"
    restart: always
    environment:
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
  db:
    container_name: postgresdb
    image: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backstage:
    container_name: backstage
    image: ibrahimnasri24/ubility-backstage:1.0.0
    hostname: backstage
    command: ["node", "packages/backend", "--config", "app-config.yaml"]
    expose:
      - "7007"
    ports:
      - "7007:7007"
    restart: always
    depends_on:
      - db
    environment:
      - JENKINS_USERNAME=${JENKINS_USERNAME}
      - JENKINS_API_TOKEN=${JENKINS_API_TOKEN}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CONTAINER_REGISTRY=${CONTAINER_REGISTRY}
      - RESOURCE_GROUP=${RESOURCE_GROUP}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
      - AUTOMATION_SERVER_JWT=${AUTOMATION_SERVER_JWT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT="5432"
      - POSTGRES_HOST="127.0.0.1"
      - APP_BASE_URL=${APP_BASE_URL}
      - BACKEND_BASE_URL=${BACKEND_BASE_URL}
      - ORIGIN=${ORIGIN}
      - AUTOMATION_SERVER_BASE_URL="aut-server"
      - JENKINS_ADDRESS=${JENKINS_ADDRESS}
      - VM_ADDRESS=${VM_ADDRESS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
volumes:
  postgres-data:
