app:
  title: Ubility Backstage
  baseUrl: http://localhost:3000

organization:
  name: UbilityAi

backend:
  # Used for enabling authentication, secret is shared by all backend plugins
  # See https://backstage.io/docs/auth/service-to-service-auth for
  # information on the format
  # auth:
  #   keys:
  #     - secret: ${BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: ibrahim
      password: 2508nnNN&nnNN
  cache:
    store: memory
  workingDirectory: /tmp

proxy:
techdocs:
  builder: 'local' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: url
      target: https://github.com/ibrahimnasri24/deploy-flask-app-backstage-template/blob/master/template.yaml
    - type: url
      target: https://github.com/ibrahimnasri24/deploy-flask-app-backstage-template/blob/master/test-template.yaml
    - type: url
      target: https://github.com/ibrahimnasri24/cluster-nginx-ingress/blob/master/template.yaml

ubility:
  container_registry: ${CONTAINER_REGISTRY}
  resource_group: ${RESOURCE_GROUP}
  azure_tenant_id: ${AZURE_TENANT_ID}
  subscription_id: ${SUBSCRIPTION_ID}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

jenkins:
  baseUrl: http://gpt.ubilityai.com:8080/
  username: ${JENKINS_USERNAME}
  apiKey: ${JENKINS_API_TOKEN}
