version: '3'
services:
  jenkins-lts:
    image: jenkins/jenkins:lts
    container_name: jenkins-lts
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    privileged: true
    user: root
    restart: always
